mode: "sim"                # "sim" for now; later "real" on Unraid
poll_interval_seconds: 15

# 10-step curves (tweak later)
hdd_thresholds: [20,25,28,30,32,34,36,38,40,42]
hdd_pwm:        [10,15,20,30,40,50,60,70,85,100]
ssd_thresholds: [25,30,35,38,40,42,45,48,50,55]
ssd_pwm:        [10,10,15,25,35,45,55,65,80,95]

single_override_hdd_c: 45
single_override_ssd_c: 60
override_pwm: 100
fallback_pwm: 10
pwm_hysteresis: 3

# Simulated drives for Mac testing
sim:
  drives:
    - { name: "sdb",    type: "HDD", temp: 33 }
    - { name: "sdc",    type: "HDD", temp: 37 }
    - { name: "nvme0n1", type: "SSD", temp: 41 }
    - { name: "sdd",    type: "HDD", temp: null }   # spun down / N/A