poll_interval_seconds: 7
hdd_thresholds:
- 30
- 32
- 35
- 38
- 40
- 42
- 44
- 45
hdd_pwm:
- 0
- 20
- 30
- 40
- 50
- 60
- 80
- 100
ssd_thresholds:
- 35
- 40
- 45
- 48
- 50
- 52
- 54
- 55
ssd_pwm:
- 0
- 20
- 30
- 40
- 55
- 70
- 85
- 100
single_override_hdd_c: 45
single_override_ssd_c: 60
override_pwm: 100
fallback_pwm: 10
pwm_hysteresis: 3
exclude_devices:
- nvme0n1
- sdb
- sdc
idle_cutoff_hdd_c: 30
idle_cutoff_ssd_c: 35
sim:
  drives:
  - name: sda
    type: HDD
    temp: 38
  - name: sdb
    type: HDD
    temp: 42
  - name: sdc
    type: SSD
    temp: 35
  - name: nvme0n1
    type: SSD
    temp: 41
auto_apply: true
auto_apply_min_interval_s: 3
auto_apply_hysteresis_duty: 5
rp:
  repo_url: https://raw.githubusercontent.com/RoBro92/fanbridge-firmware/main
  board: rp2040
log_level: INFO
