version: 2
updates:
  - package-ecosystem: pip
    directory: /container
    schedule:
      interval: weekly
    groups:
      python-runtime:
        patterns: ['*']
    open-pull-requests-limit: 5

  - package-ecosystem: npm
    directory: /frontend
    schedule:
      interval: weekly
    groups:
      frontend:
        patterns: ['*']
    open-pull-requests-limit: 5

  - package-ecosystem: docker
    directory: /container
    schedule:
      interval: weekly
    open-pull-requests-limit: 3

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
