version: "3.9"

services:
  fanbridge:
    # Build (includes RELEASE.md in image)
    build:
      context: .
      dockerfile: container/Dockerfile
    image: ghcr.io/robro92/fanbridge:latest
    environment:
      - TZ=Europe/London
    ports:
      - "8080:8080"
    volumes:
      # Persist app config
      - ./dev-appdata:/config
      # Optional: expose stable USB serial symlinks for auto-detect (ro)
      # - /dev/serial/by-id:/dev/serial/by-id:ro
      # Optional: map Unraid disks (preferred: map the directory)
      # - /var/local/emhttp:/unraid:ro
      #   (or bind the single file)
      # - /var/local/emhttp/disks.ini:/unraid/disks.ini:ro
    # Optional device mapping; leave blank if unplugged
    # devices:
    #   - "/dev/ttyACM0:/dev/ttyACM0"
    # environment:
    #   - FANBRIDGE_SERIAL_PORT=/dev/serial/by-id/usb-Your_Device
    restart: unless-stopped
