version: "3.9"

services:
  fanbridge:
    build:
      # Build from the repo root so we can copy the root .env into the image
      context: .
      dockerfile: container/Dockerfile
    image: ghcr.io/robro92/fanbridge:latest

    # Runtime env (optional)
    environment:
      - TZ=Europe/London

    # Web UI
    ports:
      - "8080:8080"

    # Appdata (so your config survives restarts)
    volumes:
      - ./dev-appdata:/config

      # If you are building/running on Unraid host itself, you can map disks.ini:
      # - /var/local/emhttp/disks.ini:/unraid/disks.ini:ro

    restart: unless-stopped