version: "3.9"

services:
  fanbridge:
    build:
      # Build using the container folder as context so COPY paths resolve
      context: ./container
      dockerfile: Dockerfile
      args:
        # Recommended: export version from RELEASE.md before building
        #   export FANBRIDGE_VERSION=$(sed -n 's/^Version:\\s*//p' ./RELEASE.md | head -1)
        - FANBRIDGE_VERSION=${FANBRIDGE_VERSION:-dev}
    image: ghcr.io/robro92/fanbridge:latest

    # Runtime env (optional)
    environment:
      - TZ=Europe/London

    # Web UI
    ports:
      - "8080:8080"

    # Appdata (so your config survives restarts)
    volumes:
      - ./dev-appdata:/config

      # If you are building/running on Unraid host itself, you can map disks.ini:
      # - /var/local/emhttp/disks.ini:/unraid/disks.ini:ro

    restart: unless-stopped
