version: "3.9"

services:
  fanbridge:
    build:
      # Build from repo root (includes RELEASE.md in image)
      context: .
      dockerfile: container/Dockerfile
    image: ghcr.io/robro92/fanbridge:latest
    environment:
      - TZ=Europe/London
    ports:
      - "8080:8080"
    volumes:
      # Persist app config
      - ./dev-appdata:/config
      # Dev-only: live-edit templates/static (uncomment locally)
      # - ./container/templates:/app/templates:ro
      # - ./container/static:/app/static:ro
      # Optional: map Unraid disks.ini
      # - /var/local/emhttp/disks.ini:/unraid/disks.ini:ro
    restart: unless-stopped
