name: Build & Publish Docker image

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Derive version tags
        id: vars
        shell: bash
        run: |
          # When building from a tag like v1.2.3, also push versioned tags
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            REF_NAME="${GITHUB_REF_NAME}"   # e.g. v1.2.3
            VERSION_NO_V="${REF_NAME#v}"   # e.g. 1.2.3
            echo "ref_name=${REF_NAME}" >> "$GITHUB_OUTPUT"
            echo "version=${VERSION_NO_V}" >> "$GITHUB_OUTPUT"
          else
            echo "ref_name=" >> "$GITHUB_OUTPUT"
            echo "version=" >> "$GITHUB_OUTPUT"
          fi

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: container/Dockerfile
          push: true
          no-cache: true
          tags: |
            ghcr.io/robro92/fanbridge:latest
            ghcr.io/robro92/fanbridge:${{ github.sha }}
            ${{ steps.vars.outputs.ref_name && format('ghcr.io/robro92/fanbridge:{0}', steps.vars.outputs.ref_name) || '' }}
            ${{ steps.vars.outputs.version && format('ghcr.io/robro92/fanbridge:{0}', steps.vars.outputs.version) || '' }}
